# Generated by Django 5.0.4 on 2024-06-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
