# Generated by Django 5.0.4 on 2024-06-25 11:11

import base.models
import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=base.models.patient_image_path),
        ),
    ]
