# Generated by Django 5.0.4 on 2024-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_patient_options_remove_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
