# Generated by Django 5.0.4 on 2024-06-25 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='relative_cell',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_district',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_id_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_province',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_sector',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='relative_village',
        ),
        migrations.AddField(
            model_name='patient',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatives', to='base.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Rwandan', 'Rwandan'), ('Other', 'Other')], default='Rwandan', max_length=50, null=True),
        ),
    ]
